### ISSUE TITLE
support for Traefik 2

### ISSUE THREAD

**Issue by alexanderadam** [guillaumebriday/my-ansible-playbook#4]
You probably knew that this would come. :wink: 

There's also [a guide for migrating](https://docs.traefik.io/v2.0/migration/v1-to-v2/).

PS: Thank you so much for your Ansible playbook! :pray: It helps a lot!

**Comment by guillaumebriday** [comment]
Hey! Yes and it's pretty awesome

I planned to do it but it's a lot of work. I need to migrate this repo in the first place, then update all my applications in the repo https://github.com/guillaumebriday/selfhosted-services

and finally all my private applications.

I do not have so much time to do it, if you could open a PR that could be so cool!

Thank you @alexanderadam

**Comment by guillaumebriday** [comment]
Ok I will need to deploy a new server this week-end, I hope I will have enough time to do it  💪

**Comment by guillaumebriday** [comment]
Ok I tried but I didn't have so enough time to understand this docs... I think they really should focus on improve their documentations because it's just so complicated.

Anyway, I will continue to work on!

**Comment by alexanderadam** [comment]
Awesome @guillaumebriday, thank you for your efforts!
I'm not sure whether it is of any relevance for you but [traefik doesn't need to have the Docker socket exposed](https://github.com/containous/traefik/issues/4174#issuecomment-537312049) if it can use a static config. And I guess if Ansible is used to configure & deploy the containers anyway, it probably can also generate the config.

This way [security issues though `docker.sock`](https://www.lvh.io/posts/dont-expose-the-docker-socket-not-even-to-a-container.html) could be avoided.

Maybe it would make sense to switch to a static config if the Traefik role has to be changed anyway.

There's more info on this [in Traefik issue 4174](https://github.com/containous/traefik/issues/4174).

I'm lost as well with the Traefik documentation, though. To be honest: I was just lucky that I found your Ansible playbook once. :pray: 
So again, thank you for your work on this. This helped me a lot (and probably helped other people too).

**Comment by alexanderadam** [comment]
I'm not quite sure whether it is helpful but I just stumbled over [these examples](https://github.com/DoTheEvo/Traefik-v2-examples).

**Comment by kyusupov33** [comment]
same there :)

**Comment by guillaumebriday** [comment]
I did it, just need to clean a bit and push it 👌

**Comment by alexanderadam** [comment]
In the meantime I had to switch to another configuration with Docker user namespaces and Docker swarm. :see_no_evil:

**Comment by guillaumebriday** [comment]
Ah ok.

It's not incompatible with the repo right ?

**Comment by guillaumebriday** [comment]
Done! https://github.com/guillaumebriday/traefik-docker-ansible/commit/27899a7fad51a6bc2a57c9fd0c8e054e32bd0826
